# Generated by Django 3.1.7 on 2021-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('air_conditioner_status', models.CharField(default='', max_length=200)),
                ('light_status', models.CharField(default='', max_length=200)),
                ('projector_status', models.CharField(default='', max_length=200)),
                ('datetime', models.CharField(default='', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
