# Generated by Django 2.1.15 on 2020-12-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_conditioner_status', models.CharField(default='', max_length=200)),
                ('light_status', models.CharField(default='', max_length=200)),
                ('projector_status', models.CharField(default='', max_length=200)),
                ('datetime', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
