# Generated by Django 3.1.7 on 2021-05-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_air_light_projector'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
