# Generated by Django 3.1.7 on 2021-05-18 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210518_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='air',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='light',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='projector',
            name='datetime',
        ),
    ]
