# Generated by Django 3.1.7 on 2021-05-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_air_projector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='air',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='light',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projector',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
