# Generated by Django 3.1.3 on 2020-11-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='published',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
        migrations.AddField(
            model_name='users',
            name='datetime',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='device_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='device_status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
