# Generated by Django 3.1.3 on 2020-11-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201111_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default='', max_length=200)),
                ('device_status', models.CharField(default='', max_length=200)),
                ('datetime', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='users',
            name='device_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='device_status',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=70),
        ),
    ]
